.TH BTH 8 "March 2025" "1.0.0" "BTH Manual"
.SH NAME
bth \- Bytes To Header Utility
.SH SYNOPSIS
.B bth
.I -i <input>
.I -o <output>
.I -f <name>
[ .I -c <count> ]
[ .B -v ]
[ .B -s ]
[ .B -t ]
[ .B --ms-sys ]
.SH DESCRIPTION
Bytes To Header Utility in C/C++
.SH OPTIONS
.TP
.B -h, --help
Display this help and exit.
.TP
.B -V, --version
Display version information and exit.
.TP
.B -i <input>
Input file.
.TP
.B -o <output>
Output file.
.TP
.B -f <name>
Name of the generated array.
.TP
.B -c <count>
Number of bytes to read.
.TP
.B -v
Enable verbose output.
.TP
.B -s
Enable silent mode.
.TP
.B -t
Enable test mode.
.TP
.B --ms-sys
Enable MS-SYS mode.
.SH EXAMPLES
.B bth
.I -i input.txt -o output.h -f result_name -c 10 -v
Clo 'input.txt' to
.SH AUTHOR
Written by MrR736.
